rm(list=ls())
self_cross_pairs_genome <- data.frame(self_species=c("Briza minor", 
                                                     "Callitriche brutia",
                                                     "Cephalanthera damasonium",
                                                     "Juncus squarrosus",
                                                     "Luzula campestris",
                                                     "Orobanche minor",
                                                     "Papaver dubium",
                                                     "Senecio vulgaris",
                                                     "Trifolium dubium",
                                                     "Trifolium fragiferum",
                                                     "Trifolium glomeratum",
                                                     "Veronica polita"),
                                      cross_species=c("Briza media",
                                                      "Callitriche stagnalis",
                                                      "Cephalanthera longifolia",
                                                      "Juncus bufonius",
                                                      "Luzula forsteri",
                                                      "Orobanche caryophylacea",
                                                      "Papaver rhoeas",
                                                      "Senecio squalidus",
                                                      "Trifolium campestre",
                                                      "Trifolium hybridum",
                                                      "Trifolium repens",
                                                      "veronia chamaedrys"),
                                      genus=c("Briza",
                                              "Calitriche",
                                              "Cenphalanthera",
                                              "Juncus",
                                              "Luzula",
                                              "Orobanche",
                                              "Papaver",
                                              "Senecio",
                                              "Trifolium",
                                              "Trifolium",
                                              "Trifolium",
                                              "Veronica"),
                                      self_2c=c(5.8,
                                                5.46,
                                                32.8,
                                                0.61,
                                                0.97,
                                                3.66,
                                                8.2,
                                                3,
                                                2.1,
                                                1.07,
                                                0.78,
                                                0.84),
                                      cross_2c=c(13,
                                                 2.99,
                                                 33.5,
                                                 2.6,
                                                 1.4,
                                                 7.13,
                                                 4.81,
                                                 1.8,
                                                 0.9,
                                                 2.17,
                                                 3,
                                                 2.98),
                                      pair=c("B. minor x B. media",
                                             "C. brutia x C. stagnalis",
                                             "C. damasonium x C. longifolia",
                                             "J. squarrosus x J. bufonius",
                                             "L. campestris x L. forsteri",
                                             "O. minor x O. caryophylaceae",
                                             "P. dubium x P. rhoeas",
                                             "S. vulgaris x S. squalidus",
                                             "T. dubium x T. campestre",
                                             "T. fragigerum x T. hybridum",
                                             "T. glomeratum x T. repens",
                                             "V. polita x V. chamaedrys"))
self_cross_pairs_genome$difference_2c <- self_cross_pairs_genome$self_2c-self_cross_pairs_genome$cross_2c

library(ggplot2)
ggplot(data= self_cross_pairs_genome, aes(x=pair, y=difference_2c, fill=genus))+
  geom_bar(stat="identity")+
  xlab("")+
  ylab("Difference in 2C DNA Content (pg)")+
  theme(axis.text.x=element_text(angle=90),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background= element_blank(),
        axis.line= element_line(colour="black"))